### ISSUE TITLE
wallet ui?

### ISSUE THREAD

**Issue by rabble** [muun/falcon#6]
there doesn't seem to be any example ui in the example app.

**Comment by champo** [comment]
Hi! We don't release the UI to avoid having bad actors upload duplicates to the stores. You can read more about our open source policy [in our blog](https://blog.muun.com/protecting-everyone-through-public-auditability/).

**Comment by esneider** [comment]
Hey @rabble, we just open-sourced the UI too!

You can read more about it [here](https://blog.muun.com/muuns-new-open-source-model/).
