### ISSUE TITLE
No lightning invoice amount?

### ISSUE THREAD

**Issue by tgienger** [muun/falcon#7]
When trying to add funds through Strike it requires the invoice to have an amount attached to it so I can't send anything to my muun wallet.

**Comment by era-coder** [comment]
I came to add the same issue

**Comment by champo** [comment]
Hi guys! We're hard at work on this and soon to release it. Thanks for reaching out.

**Comment by champo** [comment]
Our latest release add support for generating invoices with amount. If you have any feedback let us know!
